-- SQL script to set up the expenses and income tables in Supabase

-- Create the expenses table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    category TEXT NOT NULL,
    description TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    type TEXT DEFAULT 'expense'  -- Optional: mostly redundant now but good for clarity
);

-- Create the income table
CREATE TABLE IF NOT EXISTS income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    source TEXT NOT NULL,       -- Stored as 'description' in Transaction model usually, but let's keep it aligned
    description TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    category TEXT DEFAULT 'income', -- Optional: constant for income
    type TEXT DEFAULT 'income'
);

-- Note: In Supabase, you can run this in the SQL Editor.
